Задание 3
Mishavint/formal-lang-course pull request #3
Opened 2022-09-25 17:29 UTC by Mishavint

- [X] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [X] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [X] Добавить необходимые тесты.

2022-09-26 17:41 UTC, EgorOrachyov requested changes

2022-09-26 17:41 UTC, EgorOrachyov commented on project/matrix_util.py
> +from pyformlang.finite_automaton import NondeterministicFiniteAutomaton
Util априори плохое название. В этом модуле булевы матрицы -- так и стоит назвать

2022-09-26 17:41 UTC, EgorOrachyov commented on project/matrix_util.py
> +
Дублируется по логике с __init__ методом. Может сделать init просто пустым, или сделать статический factory-метод, и т.д.

```
init(self)

make_from_...()
```

2022-09-26 17:41 UTC, EgorOrachyov commented on tests/rpq_tests.py
> +from networkx import MultiDiGraph
Именование `test_*.py`

2022-09-26 17:41 UTC, EgorOrachyov commented on tests/test_matrix_util.py
> +from project.matrix_util import BoolMatrices
Файл тоже перименовать после matrix_util переименования

2022-09-27 17:42 UTC, EgorOrachyov requested changes

2022-09-27 17:42 UTC, EgorOrachyov commented on tests/test_matrix_util.py
> +from project.bool_matrices import BoolMatrices
test_matrix_util -> test_bool_matrices

2022-09-27 17:56 UTC, Mishavint commented
Там сейчас не работает датасет. Поэтому тесты падают :(

2022-09-28 19:40 UTC, EgorOrachyov approved these changes

2022-09-29 08:48 UTC, merged